[{
    "company_name":"Dados",
    "date":ISODate("2020-09-21"),
    "students_appeared":"malar,aravind,subash,vani,keerthi"
},
{
    "company_name":"Infosys",
    "date":ISODate("2020-10-12"),
    "students_appeared":"santhosh,sanjay,subin,santhrika,priya"
},
{
    "company_name":"DXC",
    "date":ISODate("2020-10-24"),
    "students_appeared":"shivani,bargavi,meena,mani,prasanth"
},
{
    "company_name":"HCL",
    "date":ISODate("2020-11-11"),
    "students_appeared":"naveen,jaya,yogi,mukesh,mugil"
},
{
    "company_name":"Zoho",
    "date":ISODate("2020-11-23"),
    "students_appeared":"barathi,shinie,shivapriya,poorani,punitha"
}]